# Form implementation generated from reading ui file 'driftControlWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtWidgets


class Ui_Form(object):
    lastText = ""

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1024, 700))
        Form.setMaximumSize(QtCore.QSize(1024, 700))
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 41))
        self.label.setObjectName("label")
        self.graphics = QtWidgets.QGraphicsView(parent=Form)
        self.graphics.setGeometry(QtCore.QRect(250, 70, 521, 541))
        self.graphics.setStyleSheet("selection-background-color: rgb(0, 0, 0);")
        self.graphics.setObjectName("graphics")
        self.closeButton = QtWidgets.QPushButton(parent=Form)
        self.closeButton.setGeometry(QtCore.QRect(910, 630, 101, 41))
        self.closeButton.setObjectName("closeButton")
        self.reortButton = QtWidgets.QPushButton(parent=Form)
        self.reortButton.setGeometry(QtCore.QRect(780, 630, 121, 41))
        self.reortButton.setObjectName("reortButton")
        self.line = QtWidgets.QLineEdit(parent=Form)
        self.line.setGeometry(QtCore.QRect(20, 630, 750, 41))
        self.line.setObjectName("lastLine")
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setGeometry(QtCore.QRect(15, 71, 221, 541))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(780, 70, 231, 541))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Drift Control"))
        self.label.setText(_translate("Form",
                                      "<html><head/><body><p><span style=\" font-size:11pt;\">Analysed Load Cases:</span></p></body></html>"))
        self.graphics.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.closeButton.setText(_translate("Form", "Close"))
        self.reortButton.setText(_translate("Form", "Report"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "New Item"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
