# Form implementation generated from reading ui file 'driftControlWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtWidgets
from PyQt6.QtCore import QObject, pyqtSignal
import numpy as np
import pyqtgraph as pg

class DriftControlWindowUi_Form(QObject):
    my_signal = pyqtSignal(str)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 700)
        Form.setMinimumSize(QtCore.QSize(1024, 700))
        Form.setMaximumSize(QtCore.QSize(1024, 700))
        Form.setWindowTitle("Drift Control")
        
        
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 240, 41))
        self.label.setText("<html><head/><body><p><span style=\" font-size:13pt;\">Analysed Load Combination:</span></p></body></html>")
        
        self.plot = pg.PlotWidget(parent=Form)
        self.plot.setGeometry(QtCore.QRect(250, 70, 440, 541))
        self.plot.addLegend()
        self.plot.setLabel('bottom', 'Level', units='m')  # x-axis label
        self.plot.setLabel('left', 'Drift', units='mm')  # y-axis label
        #self.plot.setBackground(pg.mkColor((255, 255, 255, 255)))

        
        self.closeButton = QtWidgets.QPushButton(parent=Form)
        self.closeButton.setGeometry(QtCore.QRect(870, 630, 141, 41))
        self.closeButton.setText("Close")
        
        self.reortButton = QtWidgets.QPushButton(parent=Form)
        self.reortButton.setGeometry(QtCore.QRect(700, 630, 161, 41))
        self.reortButton.setText("Report")
        
        self.line = QtWidgets.QLineEdit(parent=Form)
        self.line.setGeometry(QtCore.QRect(250, 630, 440, 41))
        self.label_name = QtWidgets.QLabel(parent=Form)
        self.label_name.setGeometry(QtCore.QRect(20, 630, 240, 41))
        self.label_name.setText("<html><head/><body><p><span style=\" font-size:12pt;\">Import Name of Reort To Save:</span></p></body></html>")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(260, 20, 420, 41))
        self.label_2.setText("<html><head/><body><p><span style=\" font-size:10pt;\">""</span></p></body></html>")
        
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setGeometry(QtCore.QRect(15, 71, 221, 541))

    
        
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(700, 70, 310, 541))


    def emit_signal(self, text):

        self.my_signal.emit(text)