# Form implementation generated from reading ui file 'driftControlWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1024, 700))
        Form.setMaximumSize(QtCore.QSize(1024, 700))
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 41))
        self.label.setObjectName("label")
        self.list = QtWidgets.QListWidget(parent=Form)
        self.list.setGeometry(QtCore.QRect(10, 70, 231, 541))
        self.list.setObjectName("list")
        self.graphics = QtWidgets.QGraphicsView(parent=Form)
        self.graphics.setGeometry(QtCore.QRect(260, 80, 501, 521))
        self.graphics.setObjectName("graphics")
        self.table = QtWidgets.QTableView(parent=Form)
        self.table.setGeometry(QtCore.QRect(780, 70, 231, 541))
        self.table.setObjectName("table")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(249, 69, 521, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.closeButton = QtWidgets.QPushButton(parent=Form)
        self.closeButton.setGeometry(QtCore.QRect(910, 630, 101, 41))
        self.closeButton.setObjectName("closeButton")
        self.reortButton = QtWidgets.QPushButton(parent=Form)
        self.reortButton.setGeometry(QtCore.QRect(780, 630, 121, 41))
        self.reortButton.setObjectName("reortButton")
        self.frame.raise_()
        self.label.raise_()
        self.list.raise_()
        self.graphics.raise_()
        self.table.raise_()
        self.closeButton.raise_()
        self.reortButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Drift Control"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">Analysed Load Cases:</span></p></body></html>"))
        self.closeButton.setText(_translate("Form", "Close"))
        self.reortButton.setText(_translate("Form", "Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
