# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class MainWindowUi_Form(object):
    
    
    def setupUi(self, Form):
        self.a = 0
        Form.setObjectName("Form")
        Form.resize(900, 600)
        Form.setMinimumSize(QtCore.QSize(900, 600))
        Form.setMaximumSize(QtCore.QSize(900, 600))
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::EditPaste")
        Form.setWindowIcon(icon)
        Form.setWindowTitle("Home")

        
        
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(330, 20, 260, 80))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">TEST PROJECT</span><span style=\" font-size:12pt;\"><br/>By Reza Karami</span></p></body></html>")
        
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Previously connected to:</span></p></body></html>")
        
        self.lineEditPreConnect = QtWidgets.QLineEdit(parent=Form)
        self.lineEditPreConnect.setGeometry(QtCore.QRect(220, 120, 660, 40))      
        self.lineEditPreConnect.setReadOnly(True)
        
        self.connectButton = QtWidgets.QPushButton(parent=Form)
        self.connectButton.setGeometry(QtCore.QRect(20, 170, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.connectButton.setFont(font)
        self.connectButton.setText("Connect And Run Model")
        
        
        self.lineEditStatus = QtWidgets.QLineEdit(parent=Form)
        self.lineEditStatus.setGeometry(QtCore.QRect(220, 170, 660, 40))
        self.lineEditStatus.setReadOnly(True)
        
        
        self.driftControlButton = QtWidgets.QPushButton(parent=Form)
        self.driftControlButton.setGeometry(QtCore.QRect(370, 290, 160, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.driftControlButton.setFont(font)
        self.driftControlButton.setText("Drift Control")
        self.driftControlButton.setDisabled(True)
        
        self.lineEditPreDrift = QtWidgets.QLineEdit(parent=Form)
        self.lineEditPreDrift.setGeometry(QtCore.QRect(20, 350, 860, 40))
        self.lineEditPreDrift.setReadOnly(True)

        
        self.closeButton = QtWidgets.QPushButton(parent=Form)
        self.closeButton.setGeometry(QtCore.QRect(770, 520, 100, 40))
        self.closeButton.setText("Close")
        
        self.pathButton = QtWidgets.QPushButton(parent=Form)
        self.pathButton.setGeometry(QtCore.QRect(600, 520, 150, 40))
        self. pathButton.setText("Set path to files")
   

    

        
        
