# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(900, 600))
        Form.setMaximumSize(QtCore.QSize(900, 600))
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::EditPaste")
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(330, 20, 261, 81))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditPreConnect = QtWidgets.QLineEdit(parent=Form)
        self.lineEditPreConnect.setGeometry(QtCore.QRect(200, 120, 681, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(28)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPreConnect.sizePolicy().hasHeightForWidth())
        self.lineEditPreConnect.setSizePolicy(sizePolicy)
        self.lineEditPreConnect.setText("")
        self.lineEditPreConnect.setReadOnly(True)
        self.lineEditPreConnect.setObjectName("lineEditPreConnect")
        self.connectButton = QtWidgets.QPushButton(parent=Form)
        self.connectButton.setGeometry(QtCore.QRect(20, 170, 161, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.connectButton.setFont(font)
        self.connectButton.setObjectName("connectButton")
        self.lineEditStatus = QtWidgets.QLineEdit(parent=Form)
        self.lineEditStatus.setGeometry(QtCore.QRect(200, 170, 681, 41))
        self.lineEditStatus.setText("")
        self.lineEditStatus.setReadOnly(True)
        self.lineEditStatus.setObjectName("lineEditStatus")
        self.driftControlButton = QtWidgets.QPushButton(parent=Form)
        self.driftControlButton.setGeometry(QtCore.QRect(370, 290, 161, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.driftControlButton.sizePolicy().hasHeightForWidth())
        self.driftControlButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.driftControlButton.setFont(font)
        self.driftControlButton.setObjectName("driftControlButton")
        self.lineEditPreDrift = QtWidgets.QLineEdit(parent=Form)
        self.lineEditPreDrift.setGeometry(QtCore.QRect(20, 350, 861, 41))
        self.lineEditPreDrift.setText("")
        self.lineEditPreDrift.setReadOnly(True)
        self.lineEditPreDrift.setObjectName("lineEditPreDrift")
        self.closeButton = QtWidgets.QPushButton(parent=Form)
        self.closeButton.setGeometry(QtCore.QRect(770, 520, 101, 41))
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(Form)
        self.closeButton.pressed.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Home"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">TEST PROJECT</span><span style=\" font-size:12pt;\"><br/>By Reza Karami</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Previously connected to:</span></p></body></html>"))
        self.connectButton.setText(_translate("Form", "Connect to Etabs"))
        self.driftControlButton.setText(_translate("Form", "Drift Control"))
        self.closeButton.setText(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
