# Form implementation generated from reading ui file 'pathWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(939, 473)
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentProperties")
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(370, 10, 211, 81))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 121, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 121, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(30, 250, 121, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(30, 310, 121, 41))
        self.label_5.setObjectName("label_5")
        self.lineEditEtabsPath = QtWidgets.QLineEdit(parent=Form)
        self.lineEditEtabsPath.setGeometry(QtCore.QRect(150, 130, 771, 41))
        self.lineEditEtabsPath.setText("")
        self.lineEditEtabsPath.setObjectName("lineEditEtabsPath")
        self.lineEditModelPath = QtWidgets.QLineEdit(parent=Form)
        self.lineEditModelPath.setGeometry(QtCore.QRect(150, 190, 771, 41))
        self.lineEditModelPath.setText("")
        self.lineEditModelPath.setObjectName("lineEditModelPath")
        self.lineEditModelName = QtWidgets.QLineEdit(parent=Form)
        self.lineEditModelName.setGeometry(QtCore.QRect(150, 250, 771, 41))
        self.lineEditModelName.setText("")
        self.lineEditModelName.setObjectName("lineEditModeNane")
        self.lineEditSavePath = QtWidgets.QLineEdit(parent=Form)
        self.lineEditSavePath.setGeometry(QtCore.QRect(150, 310, 771, 41))
        self.lineEditSavePath.setText("")
        self.lineEditSavePath.setObjectName("lineEditSavePath")
        self.exitButton = QtWidgets.QPushButton(parent=Form)
        self.exitButton.setGeometry(QtCore.QRect(800, 390, 121, 41))
        self.exitButton.setObjectName("exitButton")
        self.closeButton = QtWidgets.QPushButton(parent=Form)
        self.closeButton.setGeometry(QtCore.QRect(660, 390, 121, 41))
        self.closeButton.setObjectName("closeButton")
        self.runButton = QtWidgets.QPushButton(parent=Form)
        self.runButton.setGeometry(QtCore.QRect(520, 390, 121, 41))
        self.runButton.setObjectName("runButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Connection Settings"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Connection Setting</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p>Etabs installation<br/>path :</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p>Model file path :</p></body></html>"))
        self.label_4.setText(_translate("Form", "Model name :"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p>Folder path for<br/>saving results :</p></body></html>"))
        self.closeButton.setText(_translate("Form", " Save and Close"))
        self.runButton.setText(_translate("Form", "Save and Run"))
        self.exitButton.setText(_translate("Form", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
